### ISSUE TITLE
Make deploy to GCP storage automatic

### ISSUE THREAD

**Issue by lestrrat** [builderscon/session-timer#10]
```
make deploy
```

とかできるようにしておく（別にmakeじゃなくてもよい）

**Comment by Leko** [comment]
GCP > Development > Source Codeから設定可能な模様。
ただしオーナー権限がないとGithub等のアカウント認証ができない。

<img width="937" alt="screen shot 2016-07-08 at 3 39 49 pm" src="https://cloud.githubusercontent.com/assets/1424963/16679391/3ecb6fd2-4522-11e6-8c94-efc38e654551.png">

**Comment by Leko** [comment]
懸念点: リポジトリ内でディレクトリを1段掘っているので、`react`ディレクトリの中身をBucketに展開できるのか不明

**Comment by Leko** [comment]
↑とりあえずローカルから手動でコマンドを叩いてデプロイする方法を試してみた
