### ISSUE TITLE
disable start and interval choice buttons while timer is working

### ISSUE THREAD

**Issue by koron** [builderscon/session-timer#12]
タイマーを動かしている最中は、start と時間選択ボタンを無効化したほうが良さそうです。

確認されている問題点
-   タイマーを動かしている最中に、start ボタンを何度か押すと stop でボタンを押してもタイマーが止まらなくなる
-   タイマーを動かしている最中に、時間選択ボタンを押して時刻選択すると表記に反映されてしまう(タイマーの実際の刻限が変わるかどうかまでは未確認)

**Comment by koron** [comment]
> タイマーの実際の刻限が変わるかどうかまでは未確認

変わったっぽい。1分で開始、5分に変更、1分たっても鳴らない、って感じ。

**Comment by Leko** [comment]
報告ありがとうございます。直します
