### ISSUE TITLE
Research about real-time sync with Firebase

### ISSUE THREAD

**Issue by januswel** [builderscon/session-timer#2]
- [x] feasibility
- [x] cost

**Comment by januswel** [comment]
React Native でも Realtime Database を使えることを確認。

https://github.com/januswel/fb-rn-todo

実機でも同等のレイテンシーで動く。
認証まわりは OpenID など既存プロバイダーを使うことも可能。
自分でプロバイダー作ってそれを使うこともできるよう。

**Comment by januswel** [comment]
ちゃんと使おうとすると金銭的コストはかかるが、用途によっては無料でも問題なさそう。

https://firebase.google.com/pricing/

**Comment by lestrrat** [comment]
これcloseしちゃうと見失わない？ closeするならREADMEとかなんでもいいんだけど、誰でも見えるドキュメントにまとめるとよさそう。

**Comment by januswel** [comment]
では、 README.md に future works としてまとめますね！

**Comment by januswel** [comment]
まとめました！
