### ISSUE TITLE
Alert timings

### ISSUE THREAD

**Issue by lestrrat** [builderscon/session-timer#24]
とりあえず、案。

| Total Time | Alert Timing(s) | Notes |
| --- | --- | --- |
| 1 min | 50 secs | This is not used in real life. Only for demonstration purposes |
| 5 min | 4 min | Lightning Talks |
| 15 min | 10 min | Talks at small scale meetups tends to be this long |
| 30 min | 15 min, 25 min | Session is 20 minutes of real talk + 10 minutes of Q&A. |
| 60 min | 30 min, 45 min, 50 min | Session is 50 minutes of real talk + 10 minutes of Q&A. |

**Comment by januswel** [comment]
スマホ版 d5da9199b1fe8977535ffad523f77c72286e52bb で対応しました !!

**Comment by lestrrat** [comment]
確認とかするならこれはもうリリースしてもらったほうが早いよね？

**Comment by januswel** [comment]
そうですね。 v1.0.1 リリースします。

**Comment by januswel** [comment]
v1.0.1 リリースしました！

**Comment by Leko** [comment]
#26 待ち
