### ISSUE TITLE
Make it possible for users to know when you will receive alerts

### ISSUE THREAD

**Issue by lestrrat** [builderscon/session-timer#25]
ユーザが時間を選ぶ時にいつ画面の色が変わるのか、前持って知ってたほうがいいと思う。

refs #24

**Comment by imoans** [comment]
@januswel 

<img width="527" alt="2016-08-04 21 41 07" src="https://cloud.githubusercontent.com/assets/10163502/17422604/877cf8ae-5aee-11e6-8d5c-6c4ff93f36e5.png">

presetから、タイマーの時間をセットするときに、
モーダルでタイマー時間とアラート時間を表示するのはどうでしょうか。(左の画像)

右の画像は、タイマー画面にアラート時間を表示するとしたらの画面です。
次のアラート時間を１つずつ表示するイメージです。

**Comment by januswel** [comment]
@imoans ありがとうございますー
来週実装してみます！！

**Comment by januswel** [comment]
左のほうですね！

**Comment by januswel** [comment]
05955404c0380bd275c6bb0e7521dffde70cf3b5 で対応しました。

![presets](https://cloud.githubusercontent.com/assets/43239/17549921/94f405de-5f2d-11e6-9e40-4fe534038330.gif)

**Comment by januswel** [comment]
高さの関係もあって Set ボタンで決定ではなく、それぞれの preset 選択時に切り替えちゃう作りとしました
