### ISSUE TITLE
Presets are not in sync between native and Web

### ISSUE THREAD

**Issue by lestrrat** [builderscon/session-timer#26]
- Android版には 1, 5, 30, 60 min がある
- Web版には 1, 5, 15, 30, 60 min がある

これらの定義を共通の場所に切り出すことは可能ですか？具体的には、全体の時間とお知らせのある時間は共通であるべきかな

**Comment by januswel** [comment]
データ形式を決めてしまえば大丈夫かと思います。

現在のデータ定義場所
react 側: react/src/js/index.jsx
react-native 側: react-native/domain/presets.js

**Comment by lestrrat** [comment]
是非揃えてリリース、プリーズ！ :)

**Comment by januswel** [comment]
かしこまりましたー
@Leko さんが帰ってきたら一回ハナシます！

**Comment by Leko** [comment]
@januswel 戻りました。
どこに置きましょう、プロジェクト直下に`lib`ディレクトリでも切りますか？
それかいっそprivateなnpmパッケージ作って切りだしちゃうか。

**Comment by Leko** [comment]
@januswel すでにネイティブアプリ版は #24 に対応済みなので、コンポーネントを共通部分に持ってきて、対応済みのコンポーネントを流用して動くようこちらのソースを修正する予定です

**Comment by januswel** [comment]
@Leko ごめんなさい、確認遅れました。

> プロジェクト直下にlibディレクトリでも切りますか？

これがよい気がします。

で、音鳴らしたりする部分ですが、 Web とスマホで API が違うので、どう共通化するかですね。
ぱっと思いつく案としては、「インスタンス生成時に音を鳴らすクラスのインスタンスを DI できるPreset クラスを作る」かなぁ。

明日時間が取れるので明日で良ければこちらで実装して push します !!

**Comment by januswel** [comment]
@Leko 

> > プロジェクト直下にlibディレクトリでも切りますか？
> 
> これがよい気がします。

とか言っておいてなんですが、 React Native packager の融通が効かなすぎて結局

> それかいっそprivateなnpmパッケージ作って切りだしちゃうか。

となりました。
private にする意味もなかったので次のように。

https://www.npmjs.com/package/builderscon-session-timer-domain

サンプルはこの辺を見ていただけると…。
- import
  - https://github.com/builderscon/session-timer/blob/master/react-native/react-redux/components/app.ios.js#L15
- timer 作成
  - https://github.com/builderscon/session-timer/blob/master/react-native/react-redux/components/app.ios.js#L137
- 鳴らす音を指定する方法
  - https://github.com/builderscon/session-timer/blob/master/react-native/react-redux/components/app.ios.js#L179

Twitter でもいいですので、いつでも質問ください。

**Comment by januswel** [comment]
@Leko 

> とか言っておいてなんですが、 React Native packager の融通が効かなすぎて結局
> 
> > それかいっそprivateなnpmパッケージ作って切りだしちゃうか。
> 
> となりました。
> private にする意味もなかったので次のように。
> 
> https://www.npmjs.com/package/builderscon-session-timer-domain

ということに一旦しましたが、先ほど npm に詳しい方に聞いたところ、なんと package.json の `dependencies` は相対パス指定できるそうです。

``` json:package.json
{
  "dependencies": {
    "builderscon-session-timer-domain": "../domain"
  }
}
```

二転三転してすみません。
上記方法でまかなうとして、 publish しているのが僕個人のアカウントなので npm package のほうは消そうと思いますが大丈夫でしょうか ?

**Comment by Leko** [comment]
はい、大丈夫です。

**Comment by Leko** [comment]
↑デプロイしました
