### ISSUE TITLE
Add License/Terms of Usage

### ISSUE THREAD

**Issue by lestrrat** [builderscon/session-timer#8]
LICENSEはMITでいいとして（ただし、リンクする必要あり）、あとは以下の事を書いたページ？を用意してリンクしないと駄目かな。
- Free to use as long as builderscon link and logo are visible
- We are not responsible for any damages

**Comment by Leko** [comment]
了解です。
リンク押したら出てくるモーダルをタイマー内に入れ込むでも良いですか

**Comment by lestrrat** [comment]
良いと思いますー

**Comment by Leko** [comment]
了解です！

**Comment by Leko** [comment]
@lestrrat こんな感じでどうでしょう、PRにスクショ貼ってあります
https://github.com/builderscon/session-timer/pull/15

**Comment by lestrrat** [comment]
文章ちゃんとしないとなw

んー、イチイチこれを変えるの面倒くさいから、リンクにします？
適当にweb.timer.builderscon.io/tos.txtとかにリンクしておいて、あとで書きますかね。

**Comment by Leko** [comment]
OKです。
では、とりあえず今書いてあるものを.txtに分割してGCSに置く＋リポジトリにも足しておくので、後で良しなにお願いします

**Comment by Leko** [comment]
https://github.com/builderscon/session-timer/blob/master/react/public/tos.txt
の編集お願いします。GSCにも同名で置きましたー
